<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Normativa;

class NormativaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $normativas = [
            [
                'section' => 'General',
                'control_area' => 'Supplier Identification',
                'question_en' => 'Supplier formally identified and scoped for PUSH Srl services',
                'question_it' => 'Il fornitore è formalmente identificato e definito per i servizi erogati a PUSH Srl',
                'iso_27001_2022_reference' => 'Cl. 4.1, 4.2',
                'gdpr_reference' => 'Art. 28, 30',
                'answer' => null,
                'evidence_required' => 'Contract, service description',
                'notes' => null,
                'weight' => 1,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Governance',
                'control_area' => 'Information Security Policy',
                'question_en' => 'Formal Information Security Policy approved by management',
                'question_it' => 'È presente una Politica di Sicurezza delle Informazioni formalmente approvata dalla Direzione',
                'iso_27001_2022_reference' => 'A.5.1',
                'gdpr_reference' => 'Art. 24',
                'answer' => null,
                'evidence_required' => 'Security Policy document',
                'notes' => null,
                'weight' => 2,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Governance',
                'control_area' => 'Roles & Responsibilities',
                'question_en' => 'Security roles and responsibilities clearly defined',
                'question_it' => 'Ruoli e responsabilità in ambito sicurezza sono chiaramente definiti',
                'iso_27001_2022_reference' => 'Cl. 5.3',
                'gdpr_reference' => 'Art. 24',
                'answer' => null,
                'evidence_required' => 'Org chart, role descriptions',
                'notes' => null,
                'weight' => 2,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Access Control',
                'control_area' => 'Least Privilege',
                'question_en' => 'Access rights granted based on least privilege principle',
                'question_it' => 'I diritti di accesso sono assegnati secondo il principio del minimo privilegio',
                'iso_27001_2022_reference' => 'A.5.15',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'Access control policy',
                'notes' => null,
                'weight' => 3,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Access Control',
                'control_area' => 'Authentication',
                'question_en' => 'Strong authentication mechanisms implemented (MFA where applicable)',
                'question_it' => 'Sono implementati meccanismi di autenticazione forte (MFA ove applicabile)',
                'iso_27001_2022_reference' => 'A.5.17',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'MFA configuration, policy',
                'notes' => null,
                'weight' => 3,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'IT Security',
                'control_area' => 'Patch Management',
                'question_en' => 'Systems regularly updated with security patches',
                'question_it' => 'I sistemi sono regolarmente aggiornati con patch di sicurezza',
                'iso_27001_2022_reference' => 'A.8.8',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'Patch management logs',
                'notes' => null,
                'weight' => 2,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'IT Security',
                'control_area' => 'Malware Protection',
                'question_en' => 'Anti-malware / EDR solutions implemented',
                'question_it' => 'Sono implementate soluzioni Anti-malware / EDR',
                'iso_27001_2022_reference' => 'A.8.7',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'AV/EDR screenshots',
                'notes' => null,
                'weight' => 2,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Data Protection',
                'control_area' => 'Personal Data Processing',
                'question_en' => 'Processes personal data on behalf of PUSH Srl',
                'question_it' => 'Il fornitore tratta dati personali per conto di PUSH Srl',
                'iso_27001_2022_reference' => 'A.5.34',
                'gdpr_reference' => 'Art. 28',
                'answer' => null,
                'evidence_required' => 'DPA / Register of processing',
                'notes' => null,
                'weight' => 3,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Data Protection',
                'control_area' => 'Encryption',
                'question_en' => 'Personal data encrypted in transit and/or at rest',
                'question_it' => 'I dati personali sono cifrati in transito e/o a riposo',
                'iso_27001_2022_reference' => 'A.8.24',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'Encryption policy',
                'notes' => null,
                'weight' => 3,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Incident Management',
                'control_area' => 'Incident Response',
                'question_en' => 'Incident response procedure formally defined',
                'question_it' => 'È definita una procedura formale di gestione degli incidenti',
                'iso_27001_2022_reference' => 'A.5.24',
                'gdpr_reference' => 'Art. 33',
                'answer' => null,
                'evidence_required' => 'Incident Response Plan',
                'notes' => null,
                'weight' => 3,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Business Continuity',
                'control_area' => 'BCP / DR',
                'question_en' => 'Business Continuity and Disaster Recovery plans in place',
                'question_it' => 'Sono presenti piani di Business Continuity e Disaster Recovery',
                'iso_27001_2022_reference' => 'A.5.29',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'BCP / DR documentation',
                'notes' => null,
                'weight' => 3,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Suppliers',
                'control_area' => 'Sub-suppliers',
                'question_en' => 'Sub-suppliers identified and assessed',
                'question_it' => 'I sub-fornitori sono identificati e valutati',
                'iso_27001_2022_reference' => 'A.5.19',
                'gdpr_reference' => 'Art. 28(2)',
                'answer' => null,
                'evidence_required' => 'Supplier list and contracts',
                'notes' => null,
                'weight' => 2,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Compliance',
                'control_area' => 'Certifications',
                'question_en' => 'Security certifications available (ISO 27001, SOC 2, etc.)',
                'question_it' => 'Sono disponibili certificazioni di sicurezza (ISO 27001, ecc.)',
                'iso_27001_2022_reference' => 'Cl. 9.2',
                'gdpr_reference' => 'Art. 42',
                'answer' => null,
                'evidence_required' => 'Certificates',
                'notes' => null,
                'weight' => 1,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Risk',
                'control_area' => 'Risk Assessment',
                'question_en' => 'Risk assessment performed for provided services',
                'question_it' => 'È stata effettuata una valutazione del rischio per i servizi forniti',
                'iso_27001_2022_reference' => 'Cl. 6.1',
                'gdpr_reference' => 'Art. 32',
                'answer' => null,
                'evidence_required' => 'Risk assessment document',
                'notes' => null,
                'weight' => 2,
                'score' => 0,
                'risk_level' => 'Low',
            ],
            [
                'section' => 'Declaration',
                'control_area' => 'Supplier Declaration',
                'question_en' => 'Formal declaration signed by supplier',
                'question_it' => 'Dichiarazione formale firmata dal fornitore',
                'iso_27001_2022_reference' => 'Cl. 5.1, 7.5',
                'gdpr_reference' => 'Art. 5(2)',
                'answer' => null,
                'evidence_required' => 'Signed declaration',
                'notes' => null,
                'weight' => 1,
                'score' => 0,
                'risk_level' => 'Low',
            ],
        ];

        foreach ($normativas as $normativa) {
            Normativa::create($normativa);
        }
    }
}
